/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package org.olivier.ihm;

import javax.swing.tree.DefaultMutableTreeNode;
import javax.swing.tree.DefaultTreeModel;

/**
 *
 * @author olivier
 */
public class FramePUMLCleaner extends javax.swing.JFrame {
    
   
   private final FramePUMLCleanerControler controler;

   /**
    * Creates new form framePUMLCleaner
    */
   public FramePUMLCleaner() {
      initComponents();
      
      controler = new FramePUMLCleanerControler(jTreeFiltre);
      
      jTextFieldFichier.setText(controler.getNomFichier());
      
      final DefaultMutableTreeNode top = controler.initaliserNodes();
      final DefaultTreeModel treeModel = new DefaultTreeModel(top);
      jTreeFiltre.setModel(treeModel);
      for (int i = 0; i < jTreeFiltre.getRowCount(); i++) {
         jTreeFiltre.expandRow(i);
      }      
   }

   /**
    * This method is called from within the constructor to initialize the form.
    * WARNING: Do NOT modify this code. The content of this method is always
    * regenerated by the Form Editor.
    */
   @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelAnalyse = new javax.swing.JPanel();
        jSplitPaneAnalyse = new javax.swing.JSplitPane();
        jPanelAnalyseDroite = new javax.swing.JPanel();
        jScrollPaneAnalyseDroite = new javax.swing.JScrollPane();
        jTextAreaFichier = new javax.swing.JTextArea();
        jButtonFiltrer = new javax.swing.JButton();
        jPanelAnalyseGauche = new javax.swing.JPanel();
        jPanelHaut = new javax.swing.JPanel();
        jTextFieldMotif = new javax.swing.JTextField();
        jButtonMotif = new javax.swing.JButton();
        jPanelBas = new javax.swing.JPanel();
        jScrollPaneJTree = new javax.swing.JScrollPane();
        jTreeFiltre = new javax.swing.JTree();
        jLabelFichier = new javax.swing.JLabel();
        jTextFieldFichier = new javax.swing.JTextField();
        jButtonSelect = new javax.swing.JButton();
        jButtonLireFichier = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("PUML cleaner");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jSplitPaneAnalyse.setDividerLocation(200);

        jTextAreaFichier.setColumns(20);
        jTextAreaFichier.setRows(5);
        jScrollPaneAnalyseDroite.setViewportView(jTextAreaFichier);

        jButtonFiltrer.setText("3 - Filtrer");
        jButtonFiltrer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonFiltrerActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelAnalyseDroiteLayout = new javax.swing.GroupLayout(jPanelAnalyseDroite);
        jPanelAnalyseDroite.setLayout(jPanelAnalyseDroiteLayout);
        jPanelAnalyseDroiteLayout.setHorizontalGroup(
            jPanelAnalyseDroiteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPaneAnalyseDroite, javax.swing.GroupLayout.DEFAULT_SIZE, 335, Short.MAX_VALUE)
            .addComponent(jButtonFiltrer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanelAnalyseDroiteLayout.setVerticalGroup(
            jPanelAnalyseDroiteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelAnalyseDroiteLayout.createSequentialGroup()
                .addComponent(jButtonFiltrer)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPaneAnalyseDroite, javax.swing.GroupLayout.DEFAULT_SIZE, 263, Short.MAX_VALUE))
        );

        jSplitPaneAnalyse.setRightComponent(jPanelAnalyseDroite);

        jButtonMotif.setText("Appliquer");
        jButtonMotif.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonMotifActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelHautLayout = new javax.swing.GroupLayout(jPanelHaut);
        jPanelHaut.setLayout(jPanelHautLayout);
        jPanelHautLayout.setHorizontalGroup(
            jPanelHautLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelHautLayout.createSequentialGroup()
                .addComponent(jTextFieldMotif, javax.swing.GroupLayout.DEFAULT_SIZE, 105, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonMotif))
        );
        jPanelHautLayout.setVerticalGroup(
            jPanelHautLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelHautLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jTextFieldMotif, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(jButtonMotif))
        );

        jScrollPaneJTree.setViewportView(jTreeFiltre);

        javax.swing.GroupLayout jPanelBasLayout = new javax.swing.GroupLayout(jPanelBas);
        jPanelBas.setLayout(jPanelBasLayout);
        jPanelBasLayout.setHorizontalGroup(
            jPanelBasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
            .addGroup(jPanelBasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jScrollPaneJTree, javax.swing.GroupLayout.DEFAULT_SIZE, 299, Short.MAX_VALUE))
        );
        jPanelBasLayout.setVerticalGroup(
            jPanelBasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 263, Short.MAX_VALUE)
            .addGroup(jPanelBasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jScrollPaneJTree, javax.swing.GroupLayout.DEFAULT_SIZE, 263, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanelAnalyseGaucheLayout = new javax.swing.GroupLayout(jPanelAnalyseGauche);
        jPanelAnalyseGauche.setLayout(jPanelAnalyseGaucheLayout);
        jPanelAnalyseGaucheLayout.setHorizontalGroup(
            jPanelAnalyseGaucheLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelHaut, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanelBas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanelAnalyseGaucheLayout.setVerticalGroup(
            jPanelAnalyseGaucheLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelAnalyseGaucheLayout.createSequentialGroup()
                .addComponent(jPanelHaut, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelBas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jSplitPaneAnalyse.setLeftComponent(jPanelAnalyseGauche);

        javax.swing.GroupLayout jPanelAnalyseLayout = new javax.swing.GroupLayout(jPanelAnalyse);
        jPanelAnalyse.setLayout(jPanelAnalyseLayout);
        jPanelAnalyseLayout.setHorizontalGroup(
            jPanelAnalyseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelAnalyseLayout.createSequentialGroup()
                .addComponent(jSplitPaneAnalyse, javax.swing.GroupLayout.DEFAULT_SIZE, 541, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanelAnalyseLayout.setVerticalGroup(
            jPanelAnalyseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPaneAnalyse, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        jLabelFichier.setText("Fichier");

        jTextFieldFichier.setText("Choisir un fichier ....");

        jButtonSelect.setText("1 - Select");
        jButtonSelect.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSelectActionPerformed(evt);
            }
        });

        jButtonLireFichier.setText("2 - Lire fichier");
        jButtonLireFichier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLireFichierActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanelAnalyse, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabelFichier)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldFichier)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonSelect)
                        .addContainerGap())
                    .addComponent(jButtonLireFichier, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelFichier)
                    .addComponent(jTextFieldFichier, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonSelect))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonLireFichier)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelAnalyse, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

   private void jButtonSelectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSelectActionPerformed
      controler.selectInputFile(jTextFieldFichier);
   }//GEN-LAST:event_jButtonSelectActionPerformed

   private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
      controler.closeWindows();
   }//GEN-LAST:event_formWindowClosing

   private void jButtonLireFichierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLireFichierActionPerformed
      controler.analyseInputFile(jTextFieldFichier.getText(), jTextAreaFichier, jTreeFiltre);
   }//GEN-LAST:event_jButtonLireFichierActionPerformed

   private void jButtonFiltrerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonFiltrerActionPerformed
      controler.filterInputFile(jTextFieldFichier.getText(), jTextAreaFichier, jTreeFiltre);
   }//GEN-LAST:event_jButtonFiltrerActionPerformed

    private void jButtonMotifActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonMotifActionPerformed
        controler.selectionnerNoeud(jTextFieldMotif.getText(), jTreeFiltre);
    }//GEN-LAST:event_jButtonMotifActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonFiltrer;
    private javax.swing.JButton jButtonLireFichier;
    private javax.swing.JButton jButtonMotif;
    private javax.swing.JButton jButtonSelect;
    private javax.swing.JLabel jLabelFichier;
    private javax.swing.JPanel jPanelAnalyse;
    private javax.swing.JPanel jPanelAnalyseDroite;
    private javax.swing.JPanel jPanelAnalyseGauche;
    private javax.swing.JPanel jPanelBas;
    private javax.swing.JPanel jPanelHaut;
    private javax.swing.JScrollPane jScrollPaneAnalyseDroite;
    private javax.swing.JScrollPane jScrollPaneJTree;
    private javax.swing.JSplitPane jSplitPaneAnalyse;
    private javax.swing.JTextArea jTextAreaFichier;
    private javax.swing.JTextField jTextFieldFichier;
    private javax.swing.JTextField jTextFieldMotif;
    private javax.swing.JTree jTreeFiltre;
    // End of variables declaration//GEN-END:variables
}
